#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

<<<<<<< HEAD
[assembly: global::Android.Runtime.ResourceDesignerAttribute("Hackaton2017.Resource", IsApplication=true)]
=======
[assembly: global::Android.Runtime.ResourceDesignerAttribute("Prototype.Resource", IsApplication=true)]
>>>>>>> d71067c4b1e4b41298159f732b8665346dd2f0b9

namespace Hackaton2017
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
<<<<<<< HEAD
=======
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050001
			public const int CO2Text = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int savedText = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int textView1 = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int textView2 = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int textView3 = 2131034116;
			
			static Id()
>>>>>>> d71067c4b1e4b41298159f732b8665346dd2f0b9
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
<<<<<<< HEAD
			private Attribute()
=======
			private Id()
>>>>>>> d71067c4b1e4b41298159f732b8665346dd2f0b9
			{
			}
		}
		
<<<<<<< HEAD
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050007
			public const int address_text = 2131034119;
			
			// aapt resource value: 0x7f050004
			public const int buttonLog = 2131034116;
			
			// aapt resource value: 0x7f050003
			public const int buttonLogWithFB = 2131034115;
			
			// aapt resource value: 0x7f050006
			public const int get_address_button = 2131034118;
			
			// aapt resource value: 0x7f050000
			public const int imageLogo = 2131034112;
			
			// aapt resource value: 0x7f050005
			public const int location_text = 2131034117;
			
			// aapt resource value: 0x7f050008
			public const int testSampleText = 2131034120;
			
			// aapt resource value: 0x7f050001
			public const int textEmail = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int textpassword = 2131034114;
			
			static Id()
=======
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Left = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Right = 2130903042;
			
			static Layout()
>>>>>>> d71067c4b1e4b41298159f732b8665346dd2f0b9
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
<<<<<<< HEAD
			private Id()
=======
			private Layout()
>>>>>>> d71067c4b1e4b41298159f732b8665346dd2f0b9
			{
			}
		}
		
<<<<<<< HEAD
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Bottom = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Index = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Left = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Main = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Right = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int test = 2130903045;
			
			static Layout()
=======
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Mipmap()
>>>>>>> d71067c4b1e4b41298159f732b8665346dd2f0b9
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
<<<<<<< HEAD
			private Layout()
=======
			private Mipmap()
>>>>>>> d71067c4b1e4b41298159f732b8665346dd2f0b9
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
<<<<<<< HEAD
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
=======
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int hello = 2130968576;
			
>>>>>>> d71067c4b1e4b41298159f732b8665346dd2f0b9
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
